version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - zip -r lambda-package.zip ./ -x buildspec.yml
      - echo "Build completed"
  post_build:
    commands:
      - aws lambda update-function-code --function-name lambda_function_name --zip-file fileb://lambda-package.zip
artifacts:
  files:
    - lambda-package.zip
